### ISSUE TITLE
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'Byte'

### ISSUE THREAD

**Issue by EricLe-dev** [yucornetto/MGMatting#4]
Hi @yucornetto,

Thank you so much for this awesome work. I try training the model with a very small dataset and ran the infer.py. However, I got this error straight away `RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'Byte'`
It seemed to be from

`util.py in get_unknown_tensor_from_pred(pred, rand_width, train_mode)
    244     weight = torch.from_numpy(weight).cuda()
    245 
--> 246     weight = F.interpolate(weight, size=(H,W), mode='nearest')`

Can you please give me a small guide on how to fix it? Thank you so much!

**Comment by EricLe-dev** [comment]
Fixed by casting the tensor. Sorry for a stupid question.

**Comment by yucornetto** [comment]
Good to know your problem has been solved! Feel free to let me know if you encounter any other problem :)
