### ISSUE TITLE
How can I get pretrained model for infer demo?

### ISSUE THREAD

**Issue by FlyMoonSky** [yucornetto/MGMatting#7]
Hi, thank you for your great work, Could you supply the well pretrained model for demo?

**Comment by yucornetto** [comment]
Hi, we have uploaded pretrained weights to reproduce numbers on public benchmarks. For a general demo purpose, you can try use the RWP model. We will update the code and models (e.g., some details, fg color model) and provide an easy-to-use demo in the near feature :) Please stay tuned.

**Comment by ousinkou** [comment]
@yucornetto Sorry, I can't find the  pretrained weights.  Could you please provide the download link ?
